
server:
  time-zone: Asia/Seoul
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: member-api
  flyway:
    locations: classpath:/db/migration
    sql-migration-suffixes: sql
    baseline-on-migrate: true
    baseline-version: 0
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    exception: messages/exception
    basename: messages/validation
    encoding: UTF-8
    fallback-to-system-locale: true
  profiles:
    include: application-${spring.profiles.active}
