
spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

springfox:
  documentation:
    swagger-ui:
      enabled: false
