
spring:
  datasource:
    master:
      jdbc-url: jdbc:mariadb://localhost:3307/member_service?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=${server.time-zone}
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: dev1234!
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  documentation:
    swagger-ui:
      enabled: true
