
server:
  time-zone: Asia/Seoul
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: member-api
  datasource:
    master:
      jdbc-url: jdbc:mariadb://localhost:3307/member_service?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=${server.time-zone}
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: dev1234!
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    locations: classpath:/db/migration
    sql-migration-suffixes: ddl
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: messages/validation
    encoding: UTF-8
    fallback-to-system-locale: true
