

spring:
  application:
    name: member-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    master:
      jdbc-url: jdbc:mariadb://localhost:3307/member_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: dev1234!

  flyway:
    locations: classpath:/db/migration
    sql-migration-suffixes: ddl
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
